---

# TYPE CONVERSION

---

Like a Series, you can convert data types in a DataFrame by using the `.astype()` method, and specifying the desired data type (*if compatible*)

In [1]:
import numpy as np
import pandas as pd

In [6]:
df = pd.read_csv('Data/retail_2016_2017.csv')
sample_df = df.sample(5, random_state=2023)
sample_df

,id,date,store_nbr,family,sales,onpromotion
613709,2559653,2016-12-10,29,DAIRY,731.0,15
290251,2236195,2016-06-11,52,HOME AND KITCHEN II,0.0,0
670069,2616013,2017-01-12,10,BOOKS,0.0,0
870367,2816311,2017-05-04,3,PERSONAL CARE,404.0,5
654702,2600646,2017-01-03,29,HOME AND KITCHEN I,30.0,7

---

## Data Type Coversion on One Column

In [7]:
sample_df['sales_int'] = sample_df['sales'].astype('int')
sample_df

,id,date,store_nbr,family,sales,onpromotion,sales_int
613709,2559653,2016-12-10,29,DAIRY,731.0,15,731
290251,2236195,2016-06-11,52,HOME AND KITCHEN II,0.0,0,0
670069,2616013,2017-01-12,10,BOOKS,0.0,0,0
870367,2816311,2017-05-04,3,PERSONAL CARE,404.0,5,404
654702,2600646,2017-01-03,29,HOME AND KITCHEN I,30.0,7,30

In [8]:
sample_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, 613709 to 654702
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           5 non-null      int64
 1   date         5 non-null      object
 2   store_nbr    5 non-null      int64
 3   family       5 non-null      object
 4   sales        5 non-null      float64
 5   onpromotion  5 non-null      int64
 6   sales_int    5 non-null      int64
dtypes: float64(1), int64(4), object(2)
memory usage: 320.0+ bytes

---

## Data Type Conversion on Multiple Columns

In [9]:
df = pd.read_csv('Data/retail_2016_2017.csv')
sample_df = df.sample(5, random_state=2026)


sample_df = sample_df.astype({'date':'datetime64[ns]', 'onpromotion':'float', 'family':'category'})
sample_df

             id       date  store_nbr           family    sales  onpromotion
347474  2293418 2016-07-13          9  HOME APPLIANCES      0.0          0.0
117731  2063675 2016-03-07         12  LAWN AND GARDEN      0.0          0.0
910185  2856129 2017-05-26         47        GROCERY I  13315.0         59.0
875905  2821849 2017-05-07         35       LADIESWEAR      0.0          0.0
4886    1950830 2016-01-03         46           BEAUTY     21.0          0.0

In [10]:
sample_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, 347474 to 4886
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           5 non-null      int64
 1   date         5 non-null      datetime64[ns]
 2   store_nbr    5 non-null      int64
 3   family       5 non-null      category
 4   sales        5 non-null      float64
 5   onpromotion  5 non-null      float64
dtypes: category(1), datetime64[ns](1), float64(2), int64(2)
memory usage: 457.0 bytes

---

In [11]:
product_df = pd.DataFrame({'product_id':[1, 2, 3, 4, 5],
                           'product' : ['Dairy', 'Dairy', 'Dairy', 'Vegetables', 'Fruits'],
                           'price': ['$2.56', '$2.56', '$4.55', '$2.74', '$5.44']
                          })
product_df

   product_id     product  price
0           1       Dairy  $2.56
1           2       Dairy  $2.56
2           3       Dairy  $4.55
3           4  Vegetables  $2.74
4           5      Fruits  $5.44

In [13]:
# converting an string data type into a column, after some cleaning
product_df.assign(price = product_df.price.str.strip('$').astype('float'))

   product_id     product  price
0           1       Dairy   2.56
1           2       Dairy   2.56
2           3       Dairy   4.55
3           4  Vegetables   2.74
4           5      Fruits   5.44