---

# TRANSFORMING DATAFRAMES

---

>The `.transform()` Method can be used to perform aggregations without reshaping.
>
>   - This is useful for **calculating group-level statistics to perform row-level analysis**

In [1]:
import numpy as np
import pandas as pd

In [2]:
retail = pd.read_csv('Data/retail_2016_2017.csv')
retail.head(3)

        id        date  store_nbr      family  sales  onpromotion
0  1945944  2016-01-01          1  AUTOMOTIVE    0.0            0
1  1945945  2016-01-01          1   BABY CARE    0.0            0
2  1945946  2016-01-01          1      BEAUTY    0.0            0

In [3]:
retail.groupby('store_nbr')['sales'].sum().round()

store_nbr
1      6230011.0
2      9450837.0
3     22358869.0
4      8118802.0
5      5886265.0
6     10877588.0
7     12297471.0
8     13446564.0
9     11172895.0
10     3753463.0
11    11698482.0
12     4572198.0
13     4095138.0
14     4708914.0
15     4762224.0
16     3844399.0
17     8568612.0
18     5264843.0
19     5464728.0
20     9039040.0
21     7106763.0
22     3577596.0
23     4852867.0
24    10536839.0
25     4791598.0
26     2919931.0
27     8739034.0
28     8460657.0
29     6993613.0
30     3251354.0
31     7659121.0
32     2611299.0
33     5664121.0
34     6595031.0
35     3292171.0
36     7074044.0
37     8078656.0
38     7450493.0
39     9340397.0
40     8572111.0
41     6994842.0
42     7381752.0
43     7268992.0
44    26855593.0
45    24180009.0
46    17613767.0
47    22445864.0
48    14947697.0
49    21076999.0
50    12086584.0
51    13853573.0
52     2696170.0
53     7277044.0
54     5013667.0
Name: sales, dtype: float64

---

## 1. `.transform()` Method Example

In [4]:
retail.assign(store_sales = (retail
    .groupby('store_nbr')['sales']
    .transform('sum'))).round()

,id,date,store_nbr,family,sales,onpromotion,store_sales
0,1945944,2016-01-01,1,AUTOMOTIVE,0.0,0,6230011.0
1,1945945,2016-01-01,1,BABY CARE,0.0,0,6230011.0
2,1945946,2016-01-01,1,BEAUTY,0.0,0,6230011.0
3,1945947,2016-01-01,1,BEVERAGES,0.0,0,6230011.0
4,1945948,2016-01-01,1,BOOKS,0.0,0,6230011.0
...,...,...,...,...,...,...,...
1054939,3000883,2017-08-15,9,POULTRY,438.0,0,11172895.0
1054940,3000884,2017-08-15,9,PREPARED FOODS,155.0,1,11172895.0
1054941,3000885,2017-08-15,9,PRODUCE,2420.0,148,11172895.0
1054942,3000886,2017-08-15,9,SCHOOL AND OFFICE SUPPLIES,121.0,8,11172895.0
1054943,3000887,2017-08-15,9,SEAFOOD,16.0,0,11172895.0

---

## LABORATORY

In [11]:
premier_league = pd.read_excel('Data/premier_league_games_full.xlsx')
premier_league.head(3)

,id,league_name,season,HomeTeam,AwayTeam,HomeGoals,AwayGoals
0,1729,England Premier League,2008/2009,Manchester United,Newcastle United,1,1
1,1730,England Premier League,2008/2009,Arsenal,West Bromwich Albion,1,0
2,1731,England Premier League,2008/2009,Sunderland,Liverpool,0,1

In [12]:
performance = premier_league.assign(
    avg_team_goals = premier_league.groupby('HomeTeam')['HomeGoals'].transform('mean'),
    difference = lambda x: x['HomeGoals'] - x['avg_team_goals']
)

performance

,id,league_name,season,HomeTeam,AwayTeam,HomeGoals,AwayGoals,avg_team_goals,difference
0,1729,England Premier League,2008/2009,Manchester United,Newcastle United,1,1,2.223684,-1.223684
1,1730,England Premier League,2008/2009,Arsenal,West Bromwich Albion,1,0,2.013158,-1.013158
2,1731,England Premier League,2008/2009,Sunderland,Liverpool,0,1,1.210526,-1.210526
3,1732,England Premier League,2008/2009,West Ham United,Wigan Athletic,2,1,1.466165,0.533835
4,1733,England Premier League,2008/2009,Aston Villa,Manchester City,4,2,1.177632,2.822368
...,...,...,...,...,...,...,...,...,...
3035,4764,England Premier League,2015/2016,Southampton,Leicester City,2,2,1.763158,0.236842
3036,4765,England Premier League,2015/2016,Swansea City,Stoke City,0,1,1.421053,-1.421053
3037,4766,England Premier League,2015/2016,Tottenham Hotspur,Liverpool,0,0,1.677632,-1.677632
3038,4767,England Premier League,2015/2016,Watford,Arsenal,0,3,1.052632,-1.052632
3039,4768,England Premier League,2015/2016,West Bromwich Albion,Sunderland,1,0,1.330827,-0.330827

In [13]:
performance.groupby(['HomeTeam', 'AwayTeam']).agg({'difference':'mean'}).sort_values('difference')

                                             difference
HomeTeam                AwayTeam
Chelsea                 Bournemouth           -2.190789
Southampton             Cardiff City          -1.763158
                        Wigan Athletic        -1.763158
Leicester City          Manchester City       -1.657895
                        Bournemouth           -1.657895
...                                                 ...
Wolverhampton Wanderers Blackpool              2.912281
Fulham                  Queens Park Rangers    2.982456
Everton                 Blackpool              3.302632
Leicester City          Queens Park Rangers    3.342105
Arsenal                 Blackpool              3.986842

[932 rows x 1 columns]

In [14]:
performance.query("HomeTeam == 'Arsenal' and AwayTeam == 'Blackpool'")

,id,league_name,season,HomeTeam,AwayTeam,HomeGoals,AwayGoals,avg_team_goals,difference
870,2599,England Premier League,2010/2011,Arsenal,Blackpool,6,0,2.013158,3.986842

In [15]:
performance.query("HomeTeam == 'Arsenal' and AwayTeam == 'Blackpool'")

,id,league_name,season,HomeTeam,AwayTeam,HomeGoals,AwayGoals,avg_team_goals,difference
870,2599,England Premier League,2010/2011,Arsenal,Blackpool,6,0,2.013158,3.986842

In [16]:
performance.query("AwayTeam == 'Blackpool'")

,id,league_name,season,HomeTeam,AwayTeam,HomeGoals,AwayGoals,avg_team_goals,difference
769,2498,England Premier League,2010/2011,Wigan Athletic,Blackpool,0,4,1.115789,-1.115789
795,2524,England Premier League,2010/2011,Aston Villa,Blackpool,3,2,1.177632,1.822368
801,2530,England Premier League,2010/2011,West Ham United,Blackpool,0,0,1.466165,-1.466165
828,2557,England Premier League,2010/2011,Bolton Wanderers,Blackpool,2,2,1.368421,0.631579
849,2578,England Premier League,2010/2011,Stoke City,Blackpool,0,1,1.342105,-1.342105
870,2599,England Premier League,2010/2011,Arsenal,Blackpool,6,0,2.013158,3.986842
881,2610,England Premier League,2010/2011,Sunderland,Blackpool,0,2,1.210526,-1.210526
894,2623,England Premier League,2010/2011,Manchester City,Blackpool,1,0,2.401316,-1.401316
916,2645,England Premier League,2010/2011,West Bromwich Albion,Blackpool,3,2,1.330827,1.669173
943,2672,England Premier League,2010/2011,Everton,Blackpool,5,3,1.697368,3.302632
966,2695,England Premier League,2010/2011,Wolverhampton Wanderers,Blackpool,4,0,1.087719,2.912281
995,2724,England Premier League,2010/2011,Blackburn Rovers,Blackpool,2,2,1.289474,0.710526
1005,2734,England Premier League,2010/2011,Fulham,Blackpool,3,0,1.517544,1.482456
1051,2780,England Premier League,2010/2011,Tottenham Hotspur,Blackpool,1,1,1.677632,-0.677632
1070,2799,England Premier League,2010/2011,Manchester United,Blackpool,4,2,2.223684,1.776316
1083,2812,England Premier League,2010/2011,Newcastle United,Blackpool,0,2,1.496241,-1.496241
1099,2828,England Premier League,2010/2011,Chelsea,Blackpool,4,0,2.190789,1.809211
1110,2839,England Premier League,2010/2011,Liverpool,Blackpool,1,2,1.934211,-0.934211
1135,2864,England Premier League,2010/2011,Birmingham City,Blackpool,2,0,1.000000,1.000000

---

## ASSIGNMENT: TRANSFORM

In [21]:
transactions = pd.read_csv('Data/transactions.csv')
transactions

             date  store_nbr  transactions
0      2013-01-01         25           770
1      2013-01-02          1          2111
2      2013-01-02          2          2358
3      2013-01-02          3          3487
4      2013-01-02          4          1922
...           ...        ...           ...
83483  2017-08-15         50          2804
83484  2017-08-15         51          1573
83485  2017-08-15         52          2255
83486  2017-08-15         53           932
83487  2017-08-15         54           802

[83488 rows x 3 columns]

In [22]:
transactions = transactions.assign(
    target_pct = transactions.transactions / 2500,
    met_target = transactions.transactions / 2500 >=1,
    bonus_payable = (transactions.transactions / 2500 >=1) * 100,
    month = transactions.date.astype('datetime64[ns]').dt.month,
    day_of_week = transactions.date.astype('datetime64[ns]').dt.dayofweek
)
transactions.head()

,date,store_nbr,transactions,target_pct,met_target,bonus_payable,month,day_of_week
0,2013-01-01,25,770,0.3080,False,0,1,1
1,2013-01-02,1,2111,0.8444,False,0,1,2
2,2013-01-02,2,2358,0.9432,False,0,1,2
3,2013-01-02,3,3487,1.3948,True,100,1,2
4,2013-01-02,4,1922,0.7688,False,0,1,2

In [23]:
transactions = transactions.assign(
    store_avg_trans = transactions.groupby(['store_nbr', 'day_of_week'])['transactions'].transform('mean'),
    trans_vs_avg = lambda x: x['transactions'] - x['store_avg_trans']
)
transactions

,date,store_nbr,transactions,target_pct,met_target,bonus_payable,month,day_of_week,store_avg_trans,trans_vs_avg
0,2013-01-01,25,770,0.3080,False,0,1,1,740.245690,29.754310
1,2013-01-02,1,2111,0.8444,False,0,1,2,1870.782427,240.217573
2,2013-01-02,2,2358,0.9432,False,0,1,2,1952.652720,405.347280
3,2013-01-02,3,3487,1.3948,True,100,1,2,3142.682008,344.317992
4,2013-01-02,4,1922,0.7688,False,0,1,2,1499.569038,422.430962
...,...,...,...,...,...,...,...,...,...,...
83483,2017-08-15,50,2804,1.1216,True,100,8,1,2342.410788,461.589212
83484,2017-08-15,51,1573,0.6292,False,0,8,1,1548.448133,24.551867
83485,2017-08-15,52,2255,0.9020,False,0,8,1,1892.588235,362.411765
83486,2017-08-15,53,932,0.3728,False,0,8,1,877.214286,54.785714
83487,2017-08-15,54,802,0.3208,False,0,8,1,817.721992,-15.721992