---

# FORMATTING DATES

---

| **CODE** | **EXAMPLE** | **DESCRIPTION** | BELONG TO |
|:---|:---|:---|:---|
| `%D` | 07/14/2022 | Zero-padded date (based on OS settings | Date |
| `%Y` | 2022 | Four digit year | Date |
| `%m` | 07 | Month of the year | Date |
| `%B` | July | Full month name (*based on OS settings*) | Date |
| `%d` | 14 | Day of the month |  Date |
| `%` | 4 | Weekday number (0-6, Sunday-Saturday) |  Date |
| `%A` | Thursday | Full weekday name (*based on OS settings*) |  Date |
| `%a` | Thu | Short weekday name (*based on OS settings*) |  Date |
| `%U` | 28 | Week of the year (*starting on the first sunday*) |  Date |
| `%j` | 195 | Day of the Year |  Date |
| `%T` | 16:36:30 | Zero-padded time (*24-hour format*) |  Time |
| `%H` | 16 | Hour (*24-hour format*) |  Time |
| `%I` | 04 | Hour (*12-hour format*) |  Time |
| `%p` | PM | AM or PM (*based on OS settings*) |  Time |
| `%M` | 36 | Minute |  Time |
| `%S` | 30 | Second) |  Time |

In [1]:
import pandas as pd
import numpy as np
from datetime import datetime

In [2]:
now = datetime.now()
now

datetime.datetime(2026, 6, 17, 19, 41, 54, 396841)

In [3]:
now.strftime('%B %d %Y')

'June 17 2026'

In [4]:
retail = pd.read_parquet('../Data/retail_2016_2017.parquet')
retail.head()

        id       date  store_nbr      family  sales  onpromotion
0  1945944 2016-01-01          1  AUTOMOTIVE    0.0            0
1  1945945 2016-01-01          1   BABY CARE    0.0            0
2  1945946 2016-01-01          1      BEAUTY    0.0            0
3  1945947 2016-01-01          1   BEVERAGES    0.0            0
4  1945948 2016-01-01          1       BOOKS    0.0            0

In [5]:
retail.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1054944 entries, 0 to 1054943
Data columns (total 6 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   id           1054944 non-null  int64
 1   date         1054944 non-null  datetime64[ns]
 2   store_nbr    1054944 non-null  int64
 3   family       1054944 non-null  object
 4   sales        1054944 non-null  float64
 5   onpromotion  1054944 non-null  int64
dtypes: datetime64[ns](1), float64(1), int64(3), object(1)
memory usage: 48.3+ MB

>---
>
>The `dt.accessor` lets you use `strftime()` and `strptime` on datetimes in Pandas DataFrames
>
>- <span style='color:orange'>`strftime` stands for **String Format Time** (*converts a datetime object to a string*).
>
>- <span style='color:red'>`strptime` stands for **String Parse Time** (*converts a string to a datetime object*).

In [6]:
# copy the column 'date' as a DataFrame
df = retail[['date']].copy()

# Create variation columns of 'date'
#`%D`: Zero-padded date
#`%Y`: Four digit - Year
#`%m`: Two-digit - Month of the year
#`%B`: Full month name
#`%b`: 3-letter month name
#`%d`: Two-digit - Day of the month |  Date |
#`%`:  Weekday number (0-6, Sunday-Saturday)
#`%A`: Full weekday name
#`%a`: Short weekday name
#`%U`: Week of the year
#`%j`: Day of the Year

In [7]:
df = (df
    .assign(
        date_padded = df['date'].dt.strftime('%D'),  # (Object data type)

        
        # Standard .dt.strftime() doesn't recognize %q natively. 
        # To use it, you must first convert the datetime column to a period.
        year_quarter = df['date'].dt.to_period('Q').dt.strftime('%Y-Q%q'), # (Object data type)

        
        full_date = df['date'].dt.strftime('%a, %b-%d-%Y'), # (Object data type)
        FULL_DATE = df['date'].dt.strftime('%A, %B-%d-%Y'), # (Object data type)
        
        week_year = df['date'].dt.strftime('%U'), # (Object data type)
        WEEK_YEAR = df['date'].dt.strftime('Week: %U'), # (Object data type)
        
        day_year = df['date'].dt.strftime('%j'), # (Object data type)
        DAY_YEAR = df['date'].dt.strftime('Day: %j'), # (Object data type)

        week_day = df['date'].dt.strftime('%w'), # Sunday = 0, Saturday = 6  -  (Object data type)
        WEEK_DAY1 = df['date'].dt.day_of_week, # Monday = 0, Sunday = 6  -  # (int32 data type)
        WEEK_DAY2 = df['date'].dt.dayofweek, # Monday = 0, Sunday = 6  -  # (int32 data type)
    )
)

df

,date,date_padded,year_quarter,full_date,FULL_DATE,week_year,WEEK_YEAR,day_year,DAY_YEAR,week_day,WEEK_DAY1,WEEK_DAY2
0,2016-01-01,01/01/16,2016-Q1,"Fri, Jan-01-2016","Friday, January-01-2016",00,Week: 00,001,Day: 001,5,4,4
1,2016-01-01,01/01/16,2016-Q1,"Fri, Jan-01-2016","Friday, January-01-2016",00,Week: 00,001,Day: 001,5,4,4
2,2016-01-01,01/01/16,2016-Q1,"Fri, Jan-01-2016","Friday, January-01-2016",00,Week: 00,001,Day: 001,5,4,4
3,2016-01-01,01/01/16,2016-Q1,"Fri, Jan-01-2016","Friday, January-01-2016",00,Week: 00,001,Day: 001,5,4,4
4,2016-01-01,01/01/16,2016-Q1,"Fri, Jan-01-2016","Friday, January-01-2016",00,Week: 00,001,Day: 001,5,4,4
...,...,...,...,...,...,...,...,...,...,...,...,...
1054939,2017-08-15,08/15/17,2017-Q3,"Tue, Aug-15-2017","Tuesday, August-15-2017",33,Week: 33,227,Day: 227,2,1,1
1054940,2017-08-15,08/15/17,2017-Q3,"Tue, Aug-15-2017","Tuesday, August-15-2017",33,Week: 33,227,Day: 227,2,1,1
1054941,2017-08-15,08/15/17,2017-Q3,"Tue, Aug-15-2017","Tuesday, August-15-2017",33,Week: 33,227,Day: 227,2,1,1
1054942,2017-08-15,08/15/17,2017-Q3,"Tue, Aug-15-2017","Tuesday, August-15-2017",33,Week: 33,227,Day: 227,2,1,1
1054943,2017-08-15,08/15/17,2017-Q3,"Tue, Aug-15-2017","Tuesday, August-15-2017",33,Week: 33,227,Day: 227,2,1,1

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1054944 entries, 0 to 1054943
Data columns (total 12 columns):
 #   Column        Non-Null Count    Dtype
---  ------        --------------    -----
 0   date          1054944 non-null  datetime64[ns]
 1   date_padded   1054944 non-null  object
 2   year_quarter  1054944 non-null  object
 3   full_date     1054944 non-null  object
 4   FULL_DATE     1054944 non-null  object
 5   week_year     1054944 non-null  object
 6   WEEK_YEAR     1054944 non-null  object
 7   day_year      1054944 non-null  object
 8   DAY_YEAR      1054944 non-null  object
 9   week_day      1054944 non-null  object
 10  WEEK_DAY1     1054944 non-null  int32
 11  WEEK_DAY2     1054944 non-null  int32
dtypes: datetime64[ns](1), int32(2), object(9)
memory usage: 88.5+ MB

<br><br>

---

## LABORATORY

In [9]:
# Show year
retail['date'].dt.strftime('%Y').sample(5)

398970    2016
526517    2016
764026    2017
342812    2016
820207    2017
Name: date, dtype: object

In [10]:
# Show year with 2 digits
retail['date'].dt.strftime('%y').sample(5)

10294     16
370089    16
171981    16
371389    16
529085    16
Name: date, dtype: object

In [11]:
# Show Year-Quarter
retail['date'].dt.to_period('Q').dt.strftime('%Y-%q').sample(5)

674521    2017-1
497415    2016-4
298960    2016-2
899396    2017-2
737103    2017-1
Name: date, dtype: object

In [12]:
# Show Year-Quarter mostly used (Method 2)
retail['date'].dt.to_period('Q').dt.strftime('%Y-Q%q').sample(5)

496123    2016-Q4
243973    2016-Q2
232066    2016-Q2
12920     2016-Q1
816066    2017-Q2
Name: date, dtype: object

In [13]:
# Show date year(2 digit)-month(3 letters)-day
retail['date'].dt.strftime('%y-%b-%d').sample(5)

191054    16-Apr-17
646540    16-Dec-29
302601    16-Jun-18
280246    16-Jun-06
435013    16-Sep-01
Name: date, dtype: object