---

# ASSIGNMENT 1: PANDAS DATETIME BASICS

---

In [1]:
import pandas as pd
import numpy as np

In [2]:
transactions = pd.read_parquet('../Data/transactions.parquet')
transactions.head()

        date  store_nbr  transactions
0 2013-01-01         25           770
1 2013-01-02          1          2111
2 2013-01-02          2          2358
3 2013-01-02          3          3487
4 2013-01-02          4          1922

In [3]:
transactions.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 83488 entries, 0 to 83487
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   date          83488 non-null  datetime64[ns]
 1   store_nbr     83488 non-null  int64
 2   transactions  83488 non-null  int64
dtypes: datetime64[ns](1), int64(2)
memory usage: 1.9 MB

<br><br>

---

<br><br>

In [6]:
# find the MAX date registered
max_date = transactions['date'].max()
max_date

Timestamp('2017-08-15 00:00:00')

In [10]:
transactions = (transactions
    .assign(
        time_to_last_date = max_date - transactions.date,
        year = transactions.date.dt.year,
        month = transactions.date.dt.month,
        day_of_week = transactions.date.dt.day_of_week)
)

transactions

,date,store_nbr,transactions,time_to_last_date,year,month,day_of_week
0,2013-01-01,25,770,1687 days,2013,1,1
1,2013-01-02,1,2111,1686 days,2013,1,2
2,2013-01-02,2,2358,1686 days,2013,1,2
3,2013-01-02,3,3487,1686 days,2013,1,2
4,2013-01-02,4,1922,1686 days,2013,1,2
...,...,...,...,...,...,...,...
83483,2017-08-15,50,2804,0 days,2017,8,1
83484,2017-08-15,51,1573,0 days,2017,8,1
83485,2017-08-15,52,2255,0 days,2017,8,1
83486,2017-08-15,53,932,0 days,2017,8,1
83487,2017-08-15,54,802,0 days,2017,8,1

In [12]:
transactions['date'] = transactions['date'].dt.strftime('%Y-%B-%d')

transactions

,date,store_nbr,transactions,time_to_last_date,year,month,day_of_week
0,2013-January-01,25,770,1687 days,2013,1,1
1,2013-January-02,1,2111,1686 days,2013,1,2
2,2013-January-02,2,2358,1686 days,2013,1,2
3,2013-January-02,3,3487,1686 days,2013,1,2
4,2013-January-02,4,1922,1686 days,2013,1,2
...,...,...,...,...,...,...,...
83483,2017-August-15,50,2804,0 days,2017,8,1
83484,2017-August-15,51,1573,0 days,2017,8,1
83485,2017-August-15,52,2255,0 days,2017,8,1
83486,2017-August-15,53,932,0 days,2017,8,1
83487,2017-August-15,54,802,0 days,2017,8,1