---

# DUPLICATED INDEX VALUES

---

>It is possible to have **duplicate index values** in a Pandas Series or DataFrame
>  - Accessing this indices by their label using `.ilo[]` returns all corresponding rows
>
>---
>You can **reset the index** in a Pandas Series or DataFrame back to the default range of integers by using the `.reset_index()` method
>   - By default, the existing index will become a new column in a DataFrame

In [1]:
import numpy as np
import pandas as pd

In [ ]:
sales = [0, 5, 155, 0, 518]
items = ["coffee", "coffee", "tea", "coconut", "sugar"]

sales_series = pd.Series(data=sales, index=items, name="Sales")
sales_series

coffee       0
coffee       5
tea        155
coconut      0
sugar      518
Name: Sales, dtype: int64

In [ ]:
sales_series.loc["coffee"]

coffee    0
coffee    5
Name: Sales, dtype: int64

In [4]:
sales_series = sales_series.reset_index()
sales_series

     index  Sales
0   coffee      0
1   coffee      5
2      tea    155
3  coconut      0
4    sugar    518

---

# LABORATORY: 

---

In [ ]:
my_series = pd.Series(
    [0, 1, 2, 3, 4, 5], index=["day 0", "day 0", "day 0", "day 2", "day 2", "day 2"]
)
my_series.index

Index(['day 0', 'day 0', 'day 0', 'day 2', 'day 2', 'day 2'], dtype='object')

In [ ]:
my_series["day 0"]

day 0    0
day 0    1
day 0    2
dtype: int64

In [ ]:
my_series["day 0"][1]

/tmp/ipykernel_15090/2875445072.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  my_series['day 0'][1]

np.int64(1)

In [8]:
my_series = my_series.reset_index(drop=True)
my_series

0    0
1    1
2    2
3    3
4    4
5    5
dtype: int64

In [9]:
my_series.loc[2:4]

2    2
3    3
4    4
dtype: int64

In [10]:
my_series.iloc[2:4]

2    2
3    3
dtype: int64

In [ ]:
oil = pd.read_csv("Data/oil.csv").dropna()
oil.head()

         date  dcoilwtico
1  2013-01-02       93.14
2  2013-01-03       92.97
3  2013-01-04       93.12
4  2013-01-07       93.20
5  2013-01-08       93.21

In [ ]:
dates = np.array(oil["date"].iloc[1000:1100])
oil_array = np.array(oil["dcoilwtico"].iloc[1000:1100])

oil_series = pd.Series(data=oil_array, index=dates, name="oil_price")
oil_series

2016-12-20    52.22
2016-12-21    51.44
2016-12-22    51.98
2016-12-23    52.01
2016-12-27    52.82
              ...
2017-05-09    45.84
2017-05-10    47.28
2017-05-11    47.81
2017-05-12    47.83
2017-05-15    48.86
Name: oil_price, Length: 100, dtype: float64

In [ ]:
# Calculate the mean of the first 10 and last 10 values
mean_first = oil_series.iloc[:10].mean()
mean_last = oil_series.iloc[-10:].mean()

print(f"mean firts 10 rows: {mean_first}\nmean last 10 rows: {mean_last}")

mean firts 10 rows: 52.765
mean last 10 rows: 47.13

In [ ]:
# Grab oil prices from January 1st, 2017 to January 7th, 2017.
oil_slice = oil_series.loc["2017-01-01":"2017-01-07"]
oil_slice

2017-01-03    52.36
2017-01-04    53.26
2017-01-05    53.77
2017-01-06    53.98
Name: oil_price, dtype: float64

In [39]:
# Then revert the index of this slice back to integers
oil_slice = oil_slice.reset_index(drop=True)

In [40]:
oil_slice

0    52.36
1    53.26
2    53.77
3    53.98
Name: oil_price, dtype: float64