---

# WHY MULTIPLE TABLES

---

>---
>In tnis section we'll cover **combining multiple DataFrames**, including joining data with related fields to add new columns, and appending data with the same fields to add rows
>
>---
>
>We'll cover:
>
>
>- Combining Basics
>- Appending
>- Joining
>
>---
>
>The Goals for this section are:
>
>
>- Append the rows for similar DataFrames
>- Learn the different join types and their behaviour
>- Join DataFrames with single & multiple related fields
>
>---
>
>Why Multiple DataFrames?
>
>There are many scenarios where working with **multiple DataFrames** is necessary:
>
>- Relational Databases save space by not repeating redundant data (*Normalization*)
>- Data comes from multiple sources (*internal company data and third-party data*)
>- Multiple files can be used to store the same data split by different time periods or groups
>
>---

In [1]:
import pandas as pd

In [3]:
retail = pd.read_parquet('../Data/retail_2016_2017.parquet')
retail.head()

        id       date  store_nbr      family  sales  onpromotion
0  1945944 2016-01-01          1  AUTOMOTIVE    0.0            0
1  1945945 2016-01-01          1   BABY CARE    0.0            0
2  1945946 2016-01-01          1      BEAUTY    0.0            0
3  1945947 2016-01-01          1   BEVERAGES    0.0            0
4  1945948 2016-01-01          1       BOOKS    0.0            0

In [4]:
transactions = pd.read_parquet('../Data/transactions.parquet')
transactions.head()

        date  store_nbr  transactions
0 2013-01-01         25           770
1 2013-01-02          1          2111
2 2013-01-02          2          2358
3 2013-01-02          3          3487
4 2013-01-02          4          1922

>---
>
>This two tables come from the same database, so they share the "date" and "store_nbr" columns
>
>If you want to calculate transactions and sales by store, you need to join the tables by their related columns
>
>---