---

# ASSIGNMENT 1: APPENDING DATAFRAMES

---

In [1]:
import pandas as pd
import numpy as np

In [2]:
transactions = pd.read_csv('../Data/transactions.csv',
                                      names=['Date', 'Store_Number', 'Transaction_Count'], 
                                      header=0,
                                      skiprows=0,
                                      parse_dates=['Date'],
                                      dtype={'Store_Number':'Int8',
                                             'Transaction_Count':'Int16'}
                            ).assign(target_pct = lambda x: x.Transaction_Count/2500,
                                     met_target = lambda x: x.target_pct >= 1,
                                     bonus_payable = lambda x: x.met_target * 100,
                                     month = lambda x: x.Date.dt.month,
                                     day_of_week = lambda x: x.Date.dt.day_of_week,
                                     ).astype({'target_pct':'Float32',
                                               'month':'Int8',
                                               'day_of_week':'Int8'})
transactions

,Date,Store_Number,Transaction_Count,target_pct,met_target,bonus_payable,month,day_of_week
0,2013-01-01,25,770,0.308,False,0,1,1
1,2013-01-02,1,2111,0.8444,False,0,1,2
2,2013-01-02,2,2358,0.9432,False,0,1,2
3,2013-01-02,3,3487,1.3948,True,100,1,2
4,2013-01-02,4,1922,0.7688,False,0,1,2
...,...,...,...,...,...,...,...,...
83483,2017-08-15,50,2804,1.1216,True,100,8,1
83484,2017-08-15,51,1573,0.6292,False,0,8,1
83485,2017-08-15,52,2255,0.902,False,0,8,1
83486,2017-08-15,53,932,0.3728,False,0,8,1
83487,2017-08-15,54,802,0.3208,False,0,8,1

In [3]:
transactions_2014 = transactions.query("Date.dt.year == 2014")
display(transactions_2014.head())

transactions_2015 = transactions.query("Date.dt.year == 2015")
transactions_2015.head()

,Date,Store_Number,Transaction_Count,target_pct,met_target,bonus_payable,month,day_of_week
16908,2014-01-01,25,840,0.336,False,0,1,2
16909,2014-01-01,36,487,0.1948,False,0,1,2
16910,2014-01-02,1,1875,0.75,False,0,1,3
16911,2014-01-02,2,2122,0.8488,False,0,1,3
16912,2014-01-02,3,3350,1.34,True,100,1,3

,Date,Store_Number,Transaction_Count,target_pct,met_target,bonus_payable,month,day_of_week
34046,2015-01-01,25,2202,0.8808,False,0,1,3
34047,2015-01-02,1,1021,0.4084,False,0,1,4
34048,2015-01-02,2,1859,0.7436,False,0,1,4
34049,2015-01-02,3,3429,1.3716,True,100,1,4
34050,2015-01-02,4,1521,0.6084,False,0,1,4

In [4]:
df = pd.concat([transactions_2014, transactions_2015], 
               axis=0, 
               ignore_index=True)

display(df.head())
df.tail()

,Date,Store_Number,Transaction_Count,target_pct,met_target,bonus_payable,month,day_of_week
0,2014-01-01,25,840,0.336,False,0,1,2
1,2014-01-01,36,487,0.1948,False,0,1,2
2,2014-01-02,1,1875,0.75,False,0,1,3
3,2014-01-02,2,2122,0.8488,False,0,1,3
4,2014-01-02,3,3350,1.34,True,100,1,3

,Date,Store_Number,Transaction_Count,target_pct,met_target,bonus_payable,month,day_of_week
35479,2015-12-31,49,3828,1.5312,True,100,12,3
35480,2015-12-31,50,2948,1.1792,True,100,12,3
35481,2015-12-31,51,2892,1.1568,True,100,12,3
35482,2015-12-31,53,2300,0.92,False,0,12,3
35483,2015-12-31,54,1572,0.6288,False,0,12,3